name: Check iPhone Stock

on:
  #schedule:
   # - cron: '0 * * * *'  # 每小时运行一次，具体时间根据需要调整
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  check-stock:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 环境

    steps:
      # 1. 获取代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 使用 Python 3.9，确保兼容

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip libgdk-pixbuf2.0-0 libx11-xcb1 libxcomposite1 libxdamage1 libxi6 libxtst6 fonts-liberation libappindicator3-1 libnss3 libnspr4 libgbm1 libxrandr2
          curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get -f install -y
          pip install -r requirements.txt  # 安装所有 Python 依赖

      # 4. 检查 Chrome 版本
      - name: Check Chrome version
        run: google-chrome-stable --version

      # 5. 使用 browser-actions/setup-chrome 来自动安装 Chrome 和对应的驱动
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # 6. 运行脚本
      - name: Run inventory check script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # 从 GitHub Secrets 中读取 Telegram token
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # 从 GitHub Secrets 中读取 Telegram chat ID
        run: |
          python check_inventory.py  # 运行脚本（假设脚本名是 check_inventory.py）
