name: iPhone17 Pro Max Monitor

# 支持手动触发和定时触发
on:
  schedule:
    # 每 2 分钟运行一次
    - cron: '*/2 * * * *'
  workflow_dispatch:   # 手动触发

jobs:
  check_stock:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4️⃣ 设置 Secrets 环境变量
      - name: Set environment variables
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: echo "Secrets loaded"

      # 5️⃣ 运行库存检查脚本
      - name: Run stock monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python check_iphone.py
