name: Apple Stock Checker (curl + selenium)

on:
  schedule:
    - cron: '*/10 * * * *'   # 每10分钟运行一次
  workflow_dispatch:

jobs:
  check_stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python check_stock_curl.py
